import type { ChildrenInterface } from '@/interfaces/general'
import { neueFont } from '@/utils/fonts'
import './globals.css'
import Header from '@/components/Header'

export const metadata = {
  title: 'Kilimanjjjaro',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: ChildrenInterface) {
  return (
    <html lang='en'>
      <body
        className={`bg-kilimanjjjaro-black font-neue antialiased ${neueFont}`}
      >
        <Header />
        {children}
      </body>
    </html>
  )
}
