import type { ChildrenInterface } from '@/interfaces/general'
import { inter } from '@/utils/fonts'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }: ChildrenInterface) {
  return (
    <html lang='en'>
        <body className={`bg-black font-inter antialiased ${inter}`}>{children}</body>
    </html>
  )
}
